name: 'sentiment'
costFn: 'crossEntOne'
decisionFn: 'hardLimit'
stages:
    - 'unfold'
    - 'dict'
    - 'fold'
    - 'conv'
    - 'relu'
    - 'maxpool'
    - 'lstm2'
    - 'sigmoid'
outputs: 'sigmoid'
specs:
    - name: 'unfold'
      type: 'timeUnfold'
      inputs: 'input'
    - name: 'dict'
      type: 'lut'
      inputs: 'unfold'
      inputDim: 16547
      outputDim: 300
      initWeights: '../data/sentiment/word-embed.npy'
      learningRate: 0.0
    - name: 'fold'
      type: 'timeFold'
      inputs: 'dict'
      timespan: 60
      outputdEdX: false
    - name: 'conv'
      type: 'conv1d'
      inputs: 'fold'
      windowSize: 4
      numFilters: 1000
      numChannels: 300
      initRange: 0.01
      initSeed: 100
      learningRate: 0.01
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
      weightRegConst: 0.000005
    - name: 'relu'
      type: 'active'
      inputs: 'conv'
      activeFn: 'relu'
      outputDim: 1000
    - name: 'maxpool'
      type: 'maxpool1d'
      inputs: 'relu'
      windowSize: 3
      outputDim: 1000
    - name: 'lstm2'
      type: 'lstm'
      inputs: 'maxpool'
      inputDim: 1000
      outputDim: 500
      timespan: 60
      initRange: 0.01
      initSeed: 4
      multiOutput: false
      learningRate: 0.1
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
      weightRegConst: 0.000005
    - name: 'sigmoid'
      type: 'map'
      inputs: 'lstm2'
      activeFn: 'sigmoid'
      outputDim: 1
      initRange: 0.1
      initSeed: 7
      learningRate: 0.01
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 5.0
      learningRateAnnealConst: 0.0
      weightRegConst: 0.00005
