costFn: crossEntOne
decisionFn: hardLimit
model: all
stages:
    - name: unfold
      type: timeUnfold
    - name: dict
      type: lut
      inputDim: 16547
      outputDim: 300
      initWeights: ../data/sentiment3/word-embed-0.npy
      learningRate: 0.0
    - name: fold
      type: timeFold
      timespan: 69
    - name: dropout
      type: dropout
      dropoutRate: 0.2
      initSeed: 3
    - name: lstm.i_gate
      type: mapRecurrent
      inputsStr: 'input(0), lstm.out(-1), lstm.mem(-1)'
      outputDim: 50
      activeFn: sigmoid
      initRange: 0.1
      initSeed: 4
      biasInitConst: 1.0
      learningRate: 0.8
      momentum: 0.9
      gradientClip: 0.1
    - name: lstm.f_gate
      type: mapRecurrent
      inputsStr: 'input, lstm.out(-1), lstm.mem(-1)'
      outputDim: 50
      activeFn: sigmoid
      initRange: 0.1
      initSeed: 5
      biasInitConst: 1.0
      learningRate: 0.8
      momentum: 0.9
      gradientClip: 0.1
    - name: lstm.o_gate
      type: mapRecurrent
      inputsStr: 'input, lstm.out(-1), lstm.mem'
      outputDim: 50
      activeFn: sigmoid
      initRange: 0.1
      initSeed: 6
      biasInitConst: 1.0
      learningRate: 0.8
      momentum: 0.9
      gradientClip: 0.1
    - name: lstm.mem_in
      type: mapRecurrent
      inputsStr: 'input, lstm.out(-1)'
      outputDim: 50
      activeFn: tanh
      initRange: 0.1
      initSeed: 7
      biasInitConst: 0.0
      learningRate: 0.8
      momentum: 0.9
      gradientClip: 0.1
    - name: lstm.FC
      type: componentProdRecurrent
      inputsStr: 'lstm.f_gate, lstm.mem(-1)'
      outputDim: 50
    - name: lstm.IZ
      type: componentProdRecurrent
      inputsStr: 'lstm.i_gate, lstm.mem_in'
      outputDim: 50
    - name: lstm.mem
      type: sumRecurrent
      inputsStr: 'lstm.FC, lstm.IZ'
      numComponents: 2
      outputDim: 50
    - name: lstm.out_in
      type: activeRecurrent
      inputsStr: 'lstm.mem'
      outputDim: 50
      activeFn: tanh
    - name: lstm.out
      type: componentProdRecurrent
      inputsStr: 'lstm.o_gate, lstm.mem'
      outputDim: 50
    - name: lstm
      type: recurrent
      inputDim: 300
      outputDim: 50
      timespan: 69
      multiOutput: false
      outputStageName: 'lstm.out'
      stages:
          - lstm.i_gate
          - lstm.f_gate
          - lstm.mem_in
          - lstm.FC
          - lstm.IZ
          - lstm.mem
          - lstm.o_gate
          - lstm.out_in
          - lstm.out
    - name: sigmoid
      type: map
      activeFn: sigmoid
      inputDim: 50
      outputDim: 1
      initRange: 0.1
      initSeed: 7
      learningRate: 0.01
      gradientClip: 0.1
      weightClip: 5.0
      annealConst: 0.0
      weightRegConst: 0.00005
    - name: all
      type: sequential
      stages:
          - unfold
          - dict
          - fold
          - dropout
          - lstm
          - sigmoid