costFn: crossEntOne
decisionFn: hardLimit
model: all
stages:
    - name: unfold
      type: timeUnfold
    - name: dict
      type: lut
      inputDim: 16547
      outputDim: 300
      initWeights: ../data/sentiment3/word-embed-0.npy
      learningRate: 0.0
      gradientClip: 5.0
      weightRegConst: 0.00005
    - name: fold
      type: timeFold
      timespan: 69
    - name: dropout
      type: dropout
      dropoutRate: 0.2
      initSeed: 3
    - name: lstm
      type: lstm
      inputDim: 300
      outputDim: 50
      timespan: 69
      initRange: 0.1
      initSeed: 4
      cutOffZeroEnd: true
      multiErr: false
      learningRate: 0.8
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 40.0
      weightRegConst: 0.00005
      learningRateAnnealConst: 0.0
      outputdEdX: false
    - name: sigmoid
      type: map
      activeFn: sigmoid
      inputDim: 50
      outputDim: 1
      initRange: 0.1
      initSeed: 7
      learningRate: 0.01
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 5.0
      learningRateAnnealConst: 0.0
      weightRegConst: 0.00005
    - name: all
      type: sequential
      stages:
          - unfold
          - dict
          - fold
          - dropout
          - lstm
          - sigmoid