costFn: crossEntIdx
decisionFn: argmax
model: all
stages:
    - name: 'imgSel'
      type: selectorRecurrent
      inputsStr: 'input'
      start: 0
      end: 1
    - name: 'txtSel'
      type: selectorRecurrent
      inputsStr: 'input'
      start: 1
      end: 2
    - name: 'imgFeat'
      type: lutRecurrent
      inputsStr: 'imgSel'
      inputDim: 1449
      outputDim: 120
      initRange: 0.1
      initSeed: 0
      learningRate: 0.0
      outputdEdX: false
    - name: 'txtDict'
      type: lutRecurrent
      inputsStr: 'txtSel'
      inputDim: 871
      outputDim: 5
      initRange: 0.1
      initSeed: 3
      learningRate: 0.0
      outputdEdX: false
    - name: 'imgRehape'
      type: reshapeRecurrent
      inputsStr: 'imgFeat'
      reshapeFn: '(x[0], 12, x[1]/12)'
    - name: 'attReshape'
      type: reshapeRecurrent
      inputsStr: 'att(-1)'
      reshapeFn: '(x[0], x[1], 1)'
    - name: 'attCtx'
      type: sumProdRecurrent
      inputsStr: 'attReshape, imgRehape'
      sumAxis: 1
      outputDim: 10
    - name: 'attCtxMLP1'
      type: mapRecurrent
      inputsStr: 'attCtx'
      outputDim: 5
      activeFn: tanh
      initRange: 0.1
      initSeed: 4
      learningRate: 0.1
    - name: 'attCtxOut'
      type: mapRecurrent
      inputsStr: 'attCtxMLP1'
      outputDim: 5
      activeFn: tanh
      initRange: 0.1
      initSeed: 5
      learningRate: 0.1
    - name: 'lstm.I'
      type: mapRecurrent
      inputsStr: 'txtDict, attCtxOut, lstm.C(-1), lstm.H(-1)'
      outputDim: 10
      activeFn: sigmoid
      initRange: 0.1
      initSeed: 6
      biasInitConst: 1.0
      learningRate: 0.1
    - name: 'lstm.F'
      type: mapRecurrent
      inputsStr: 'txtDict, attCtxOut, lstm.C(-1), lstm.H(-1)'
      outputDim: 10
      activeFn: sigmoid
      initRange: 0.1
      initSeed: 6
      biasInitConst: 1.0
      learningRate: 0.1
    - name: 'lstm.Z'
      type: mapRecurrent
      inputsStr: 'txtDict, attCtxOut, lstm.H(-1)'
      outputDim: 10
      activeFn: tanh
      initRange: 0.1
      initSeed: 6
      biasInitConst: 0.0
      learningRate: 0.1
    - name: 'lstm.O'
      type: mapRecurrent
      inputsStr: 'txtDict, attCtxOut, lstm.C, lstm.H(-1)'
      outputDim: 10
      activeFn: sigmoid
      initRange: 0.1
      initSeed: 6
      biasInitConst: 1.0
      learningRate: 0.1
    - name: 'lstm.FC'
      type: componentProdRecurrent
      inputsStr: 'lstm.F, lstm.C(-1)'
      outputDim: 10
    - name: 'lstm.IZ'
      type: componentProdRecurrent
      inputsStr: 'lstm.I, lstm.Z'
      outputDim: 10
    - name: 'lstm.C'
      type: sumRecurrent
      inputsStr: 'lstm.FC, lstm.IZ'
      numComponents: 2
      outputDim: 10
    - name: 'lstm.U'
      type: activeRecurrent
      inputsStr: 'lstm.C'
      activeFn: tanh
      outputDim: 10
    - name: 'lstm.H'
      type: componentProdRecurrent
      inputsStr: 'lstm.O, lstm.U'
      outputDim: 10
    - name: 'att'
      type: mapRecurrent
      inputsStr: 'lstm.H'
      outputDim: 12
      activeFn: tanh
      #defaultValue: 0.0
      defaultValue: 0.08333333333333
      initRange: 0.1
      initSeed: 6
      learningRate: 0.1
    - name: 'attModel'
      type: recurrent
      stages:
          - 'imgSel'
          - 'txtSel'
          - 'imgFeat'
          - 'txtDict'
          - 'imgRehape'
          - 'attReshape'
          - 'attCtx'
          - 'attCtxMLP1'
          - 'attCtxOut'
          - 'lstm.I'
          - 'lstm.F'
          - 'lstm.Z'
          - 'lstm.FC'
          - 'lstm.IZ'
          - 'lstm.C'
          - 'lstm.O'
          - 'lstm.U'
          - 'lstm.H'
          - 'att'
      outputStageName: 'lstm.H'
      inputDim: 2
      inputType: int
      outputDim: 10
      timespan: 27
      multiOutput: false
      outputdEdX: false
    - name: 'answer'
      type: map
      inputDim: 10
      outputDim: 63
      activeFn: softmax
      initRange: 0.1
      initSeed: 6
      learningRate: 0.01
    - name: 'all'
      type: sequential
      stages:
          - 'attModel'
          - 'answer'





