costFn: crossEntOne
decisionFn: hardLimit
model: all
seed: 1000
stages:
    - name: unfold
      type: timeUnfold
    - name: dict
      type: linearDict
      inputDim: 16547
      outputDim: 300
      initWeights: ../data/sentiment3/word-embed-0.npy
      learningRate: 0.0
    - name: fold
      type: timeFold
      timespan: 69
    - name: dropout1
      type: dropout
      dropoutRate: 0.2
      initSeed: 3
    - name: lstm1
      type: lstm
      inputDim: 300
      outputDim: 50
      initRange: 0.1
      initSeed: 4
      cutOffZeroEnd: true
      multiErr: true
      learningRate: 0.8
      gradientClip: 0.1
      weightClip: 20.0
      weightRegConst: 0.00005
      annealConst: 0.0
      outputdEdX: false
    - name: dropout2
      type: dropout
      dropoutRate: 0.5
      initSeed: 5
    - name: lstm2
      type: lstm
      inputDim: 50
      outputDim: 50
      initRange: 0.1
      initSeed: 6
      cutOffZeroEnd: true
      multiErr: false
      learningRate: 0.8
      gradientClip: 0.1
      weightClip: 20.0
      weightRegConst: 0.00005
      annealConst: 0.0
      outputdEdX: true
    - name: sigmoid
      type: map
      activeFn: sigmoid
      inputDim: 50
      outputDim: 1
      initRange: 0.1
      initSeed: 7
      learningRate: 0.01
      gradientClip: 0.1
      weightClip: 5.0
      annealConst: 0.0
      weightRegConst: 0.00005
    - name: all
      type: sequential
      stages:
          - unfold
          - dict
          - fold
          - dropout1
          - lstm1
          - sigmoid
trainOpt:
    numEpoch: 100
    heldOutRatio: 0.1
    xvalidNo: 0
    needValid: true
    batchSize: 25
    shuffle: true
    writeRecord: true
    saveModel: true
    plotFigs: true
    everyEpoch: true
    calcError: true
    stopCost: 0.01
    progress: true