costFn: crossEntOne
decisionFn: hardLimit
stages:
    - type: timeUnfold
    - type: linearDict
      inputDim: 816
      outputDim: 30
      initWeights: ../data/sentiment/word-embed-30.npy
      learningRate: 0.0
    - type: timeFold
      timespan: 38
    - type: dropout
      dropoutRate: 0.2
      initSeed: 3
    - type: lstm
      inputDim: 30
      outputDim: 30
      initRange: 0.1
      initSeed: 4
      cutOffZeroEnd: true
      multiErr: true
      learningRate: 0.8
      gradientClip: 0.1
      weightClip: 10.0
      weightRegConst: 0.00005
      annealConst: 0.01
      outputdEdX: false    
    - type: dropout
      dropoutRate: 0.5
      initSeed: 5
    - type: lstm
      inputDim: 30
      outputDim: 30
      initRange: 0.1
      initSeed: 6
      cutOffZeroEnd: true
      multiErr: false
      learningRate: 0.8
      gradientClip: 0.1
      weightClip: 20.0
      weightRegConst: 0.00005
      annealConst: 0.01
      outputdEdX: true
    - type: sigmoid
      inputDim: 30
      outputDim: 1
      initRange: 0.1
      initSeed: 7
      learningRate: 0.01
      gradientClip: 0.1
      weightClip: 1
      annealConst: 0.01
      weightRegConst: 0.00005
trainOpt:
    numEpoch: 2000
    heldOutRatio: 0.1
    xvalidNo: 0
    needValid: true
    momentum: 0.9
    batchSize: 20
    learningRateDecay: 1.0
    momentumEnd: 0.9
    shuffle: true
    writeRecord: true
    saveModel: true
    plotFigs: true
    everyEpoch: true
    calcError: true
    stopCost: 0.01
    progress: true
    displayDw: -1
