costFn: crossEntOne
decisionFn: hardLimit
stages:
    - type: timeUnfold
    - type: linearDict
      inputDim: 16547
      outputDim: 4096
      initSeed: 2
      initRange: 0.1
      learningRate: 0.0
      gradientClip: 5.0
      weightRegConst: 0.00005
    - type: timeFold
      timespan: 69
    - type: dropout
      dropoutRate: 0.2
      initSeed: 3
    - type: lstm
      inputDim: 4096
      outputDim: 50
      initRange: 0.1
      initSeed: 4
      cutOffZeroEnd: true
      multiErr: false
      learningRate: 0.8
      gradientClip: 0.1
      weightClip: 40.0
      weightRegConst: 0.00005
      learningRateAnnealConst: 0.0
      outputdEdX: false
    - type: map
      name: sigmoid
      activeFn: sigmoid
      inputDim: 50
      outputDim: 1
      initRange: 0.1
      initSeed: 7
      learningRate: 0.01
      gradientClip: 0.1
      weightClip: 5.0
      learningRateAnnealConst: 0.0
      weightRegConst: 0.00005
trainOpt:
    numEpoch: 2000
    heldOutRatio: 0.1
    xvalidNo: 0
    needValid: true
    momentum: 0.9
    batchSize: 25
    learningRateDecay: 1.0
    momentumEnd: 0.9
    shuffle: true
    writeRecord: true
    saveModel: true
    plotFigs: true
    everyEpoch: true
    calcError: true
    stopCost: 0.01
    progress: true
    displayDw: 4