costFn: crossEntOne 
decisionFn: hardLimit
model: all
stages:
    - name: timeUnfold
      type: timeUnfold
    - name: linearDict
      type: linearDict
      inputDim: 816
      outputDim: 30
      initWeights: ../data/sentiment/word-embed-30.npy
      learningRate: 0.0
    - name: timeFold
      type: timeFold
      timespan: 38
    - name: dropout1
      type: dropout
      dropoutRate: 0.2
      initSeed: 3
    - name: lstm1
      type: lstm
      inputDim: 30
      outputDim: 30
      initRange: 0.1
      initSeed: 4
      cutOffZeroEnd: true
      multiErr: true
      learningRate: 0.8
      learningRateAnnealConst: 0.0
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 10.0
      weightRegConst: 0.00005
      outputdEdX: false
    - name: dropout2
      type: dropout
      dropoutRate: 0.5
      initSeed: 5
    - name: lstm2
      type: lstm
      inputDim: 30
      outputDim: 30
      initRange: 0.1
      initSeed: 6
      cutOffZeroEnd: true
      multiErr: false
      learningRate: 0.8
      learningRateAnnealConst: 0.0
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 20.0
      weightRegConst: 0.00005
      outputdEdX: true
    - name: sigmoid
      type: map
      activeFn: sigmoid
      inputDim: 30
      outputDim: 1
      initRange: 0.1
      initSeed: 7
      learningRate: 0.01
      learningRateAnnealConst: 0.0
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 1
      weightRegConst: 0.00005
    - name: all
      type: sequential
      stages:
          - timeUnfold
          - linearDict
          - timeFold
          - dropout1
          - lstm1
          - dropout2
          - lstm2
          - sigmoid
trainOpt:
    numEpoch: 2000
    heldOutRatio: 0.1
    xvalidNo: 0
    needValid: true
    batchSize: 20
    shuffle: true
    writeRecord: true
    saveModel: true
    plotFigs: true
    everyEpoch: true
    calcError: true
    stopCost: 0.01
    progress: true
    displayDw: 7
