trainOpt:
    numEpoch: 100
    heldOutRatio: 0.1
    xvalidNo: 0
    needValid: true
    batchSize: 25
    shuffle: true
    writeRecord: true
    saveModel: true
    plotFigs: true
    everyEpoch: true
    calcError: true
    stopCost: 0.01
    progress: true