costFn: 'crossEntIdx'
decisionFn: 'argmax'
stages:
    - 'imgSel'
    - 'txtSel'
    - 'txtDict'
    - 'txtFold'
    - 'imgFeat'
    - 'imgMapFirst'
    - 'imgMapLast'
    - 'imgFoldFirst'
    - 'imgFoldLast'
    - 'concat'
    - 'concatRev'
    - 'concatLast'
    - 'concatLastRev'
    - 'dropoutForward'
    - 'dropoutBackward'
    - 'lstmF'
    - 'lstmB'
    - 'hidden1'
    - 'answer'
outputs: 'answer'
specs:
    - name: 'imgSel'
      type: 'selector'
      inputs: 'input'
      start: 0
      end: 1
      axis: 1
    - name: 'txtSel'
      type: 'selector'
      inputs: 'input'
      start: 1
      end: 28
      axis: 1
    - name: 'txtDict'
      type: 'lut'
      inputs: 'txtSel'
      inputDim: 871
      outputDim: 500
      initWeights: '../data/daquar-37/word_embed_coco.npy'
      learningRate: 0.0
      outputdEdX: false
    - name: 'txtFold'
      type: 'timeFold'
      inputs: 'txtDict'
      timespan: 27
    - name: 'imgFeat'
      type: 'lut'
      inputs: 'imgSel'
      inputDim: 1449
      outputDim: 4096
      initWeights: '../../../data/nyu-depth/hidden7_oxford_ms.npy'
      learningRate: 0.0
      outputdEdX: false
    - name: 'imgMapFirst'
      type: 'map'
      inputs: 'imgFeat'
      activeFn: 'identity'
      outputDim: 500
      bias: false
      initWeights: '../../../data/mscoco/coco_b2i2w_weights.h5'
      format: 'h5'
      h5key: 'imgMapFirst'
      learningRate: 0.0
    - name: 'imgMapLast'
      type: 'map'
      inputs: 'imgFeat'
      activeFn: 'identity'
      outputDim: 500
      bias: false
      initWeights: '../../../data/mscoco/coco_b2i2w_weights.h5'
      format: 'h5'
      h5key: 'imgMapLast'
      learningRate: 0.0
    - name: 'imgFoldFirst'
      type: 'timeFold'
      inputs: 'imgMapFirst'
      timespan: 1
    - name: 'imgFoldLast'
      type: 'timeFold'
      inputs: 'imgMapLast'
      timespan: 1
    - name: 'concat'
      type: 'concat'
      inputs: 'imgFoldFirst, txtFold'
      axis: 1
    - name: 'concatRev'
      type: 'timeReverse'
      inputs: 'concat'
    - name: 'concatLast'
      type: 'concat'
      inputs: 'imgFoldLast, concatRev'
      axis: 1
    - name: 'concatLastRev'
      type: 'timeReverse'
      inputs: 'concatLast'
    - name: 'dropoutForward'
      type: 'dropout'
      inputs: 'concatLastRev'
      dropoutRate: 0.4
      initSeed: 3
      outputDim: 500
    - name: 'dropoutBackward'
      type: 'dropout'
      inputs: 'concatLast'
      dropoutRate: 0.4
      initSeed: 4
      outputDim: 500
    - name: 'lstmF'
      type: 'lstm'
      inputs: 'dropoutForward'
      inputDim: 500
      outputDim: 150
      timespan: 29
      multiOutput: false
      initWeights: '../../../data/mscoco/coco_b2i2w_weights.h5'
      format: 'h5'
      h5key: 'lstmF'
      learningRate: 0.0
    - name: 'lstmB'
      type: 'lstm'
      inputs: 'dropoutBackward'
      inputDim: 500
      outputDim: 150
      timespan: 29
      multiOutput: false
      initWeights: '../../../data/mscoco/coco_b2i2w_weights.h5'
      format: 'h5'
      h5key: 'lstmB'
      learningRate: 0.0
    - name: 'hidden1'
      type: 'map'
      inputs: 'lstmF, lstmB'
      outputDim: 150
      activeFn: 'tanh'
      initRange: 0.1
      initSeed: 7
      learningRate: 0.1
      momentum: 0.9
      weightClip: 50.0
      weightRegConst: 0.00005
      outputdEdX: false
    - name: 'answer'
      type: 'map'
      inputs: 'hidden1'
      outputDim: 67
      activeFn: 'softmax'
      initRange: 0.1
      initSeed: 6
      learningRate: 0.1
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 30.0
      weightRegConst: 0.00005
