name: 'bow'
costFn: 'crossEntIdx'
decisionFn: 'argmax'
stages:
    - 'txtSel'
    - 'txtUnfold'
    - 'txtDict'
    - 'txtFold'
    - 'bow'
    - 'softmax'
outputs: 'softmax'
specs:
    - name: 'txtSel'
      type: 'selector'
      inputs: 'input'
      start: 1
      end: 28
      axis: 1
    - name: 'txtUnfold'
      type: 'timeUnfold'
      inputs: 'txtSel'
      outputdEdX: false
    - name: 'txtDict'
      type: 'lut'
      inputs: 'txtUnfold'
      intConversion: true
      inputDim: 868
      outputDim: 300
      initRange: 1.0
      initSeed: 2
      learningRate: 0.8
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 500.0
    - name: 'txtFold'
      type: 'timeFold'
      inputs: 'txtDict'
      timespan: 27
    - name: 'bow'
      type: 'sum2'
      inputs: 'txtFold'
      numComponents: 27
      outputDim: 300
    - name: 'softmax'
      type: 'map'
      inputs: 'bow'
      activeFn: 'softmax'
      outputDim: 67
      initRange: 0.1
      initSeed: 7
      learningRate: 0.01
      learningRateAnnealConst: 0.0
      momentum: 0.9
      gradientClip: 0.01
      weightClip: 5.0
      weightRegConst: 0.00005