costFn: 'crossEntIdx'
decisionFn: 'argmax'
stages:
    - 'imgSel'
    - 'txtSel'
    - 'txtDict'
    - 'txtFold'
    - 'imgFeat'
    - 'imgMapFirst'
    - 'imgMapLast'
    - 'imgFoldFirst'
    - 'imgFoldLast'
    - 'concat'
    - 'concatRev'
    - 'concatLast'
    - 'concatLastRev'
    - 'dropout'
    - 'lstm'
    - 'answer'
outputs: 'answer'
specs:
    - name: 'imgSel'
      type: 'selector'
      inputs: 'input'
      start: 0
      end: 1
      axis: 1
    - name: 'txtSel'
      type: 'selector'
      inputs: 'input'
      start: 1
      end: 46
      axis: 1
    - name: 'txtDict'
      type: 'lut'
      inputs: 'txtSel'
      inputDim: 4106
      outputDim: 300
      initWeights: '../data/cocoqa/word-embed-q.npy'
      learningRate: 0.0
      outputdEdX: false
    - name: 'txtFold'
      type: 'timeFold'
      inputs: 'txtDict'
      timespan: 45
    - name: 'imgFeat'
      type: 'lut'
      inputs: 'imgSel'
      inputDim: 6600
      outputDim: 4096
      initWeights: '../data/cocoqa/hidden7-toy.txt'
      format: plain
      learningRate: 0.0
      outputdEdX: false
    - name: 'imgMapFirst'
      type: 'map'
      inputs: 'imgFeat'
      activeFn: 'identity'
      outputDim: 300
      initRange: 0.1
      initSeed: 1
      learningRate: 0.8
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
      outputdEdX: false
    - name: 'imgMapLast'
      type: 'map'
      inputs: 'imgFeat'
      activeFn: 'identity'
      outputDim: 300
      initRange: 0.1
      initSeed: 15
      learningRate: 0.8
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
      outputdEdX: false
    - name: 'imgFoldFirst'
      type: 'timeFold'
      inputs: 'imgMapFirst'
      timespan: 1
    - name: 'imgFoldLast'
      type: 'timeFold'
      inputs: 'imgMapLast'
      timespan: 1
    - name: 'concat'
      type: 'concat'
      inputs: 'imgFoldFirst, txtFold'
      axis: 1
    - name: 'concatRev'
      type: 'timeReverse'
      inputs: 'concat'
    - name: 'concatLast'
      type: 'concat'
      inputs: 'imgFoldLast, concatRev'
      axis: 1
    - name: 'concatLastRev'
      type: 'timeReverse'
      inputs: 'concatLast'
    - name: 'dropout'
      type: 'dropout'
      inputs: 'concatLastRev'
      dropoutRate: 0.2
      initSeed: 3
      outputDim: 300
    - name: 'lstm'
      type: 'lstm'
      inputs: 'dropout'
      inputDim: 300
      outputDim: 150
      timespan: 47
      initRange: 0.1
      initSeed: 5
      cutOffZeroEnd: true
      multiOutput: false
      learningRate: 0.8
      learningRateAnnealConst: 0.0
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
      outputdEdX: true 
    - name: 'answer'
      type: 'map'
      inputs: 'lstm'
      outputDim: 298
      activeFn: 'softmax'
      initRange: 0.1
      initSeed: 6
      learningRate: 0.01
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 15.0
