name: 'imgword'
costFn: 'crossEntIdx'
decisionFn: 'argmax'
stages:
    - 'imgSel'
    - 'txtSel'
    - 'txtUnfold'
    - 'txtDict'
    - 'txtFold'
    - 'imgMaxPool'
    - 'imgFC1'
    - 'imgFC2'
    - 'imgFeatNorm'
    - 'imgMapFirst'
    - 'imgMapLast'
    - 'imgFoldFirst'
    - 'imgFoldLast'
    - 'concat'
    - 'concatRev'
    - 'concatLast'
    - 'concatLastRev'
    - 'dropout'
    - 'lstm'
    - 'softmax'
outputs: 'softmax'
specs:
    - name: 'imgSel'
      type: 'selector'
      inputs: 'input'
      start: 0
      end: 1
      axis: 1
    - name: 'txtSel'
      type: 'selector'
      inputs: 'input'
      start: 1
      end: 28
      axis: 1
    - name: 'imgMaxPool'
      type: 'lut'
      inputs: 'imgSel'
      inputDim: 1449
      outputDim: 25088
      initWeights: '/ais/gobi3/u/mren/data/nyu-depth/hidden_oxford.h5'
      format: 'h5'
      h5key: 'hidden5_maxpool'
      learningRate: 0.0
      outputdEdX: false
    - name: 'imgFC1'
      type: 'map'
      inputs: 'imgMaxPool'
      activeFn: 'relu'
      inputDim: 25088
      outputDim: 4096
      initWeights: '/ais/gobi3/u/mren/models/oxford_vgg/weights.h5'
      format: 'h5'
      h5key: 'hidden56'
      learningRate: 0.01
      momentum: 0.9
      weightRegConst: 0.000005
      gradientClip: 5.0
      weightClip: 100.0
    - name: 'imgFC2'
      type: 'map'
      inputs: 'imgFC1'
      activeFn: 'relu'
      inputDim: 4096
      outputDim: 4096
      initWeights: '/ais/gobi3/u/mren/models/oxford_vgg/weights.h5'
      format: 'h5'
      h5key: 'hidden67'
      learningRate: 0.01
      momentum: 0.9
      weightRegConst: 0.000005
      gradientClip: 5.0
      weightClip: 100.0
    - name: 'imgFeatNorm'
      type: 'normalize'
      inputs: 'imgFC2'
      mean: '/ais/gobi3/u/mren/models/coco_vgg/mean.npy'
      std: '/ais/gobi3/u/mren/models/coco_vgg/std.npy'
      outputDim: 4096
    - name: 'imgMapFirst'
      type: 'map'
      inputs: 'imgFeatNorm'
      activeFn: 'identity'
      bias: false
      outputDim: 500
      initRange: 0.05
      initSeed: 1
      learningRate: 0.8
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
    - name: 'imgMapLast'
      type: 'map'
      inputs: 'imgFeatNorm'
      activeFn: 'identity'
      bias: false
      outputDim: 500
      initRange: 0.05
      initSeed: 100
      learningRate: 0.8
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
    - name: 'imgFoldFirst'
      type: 'timeFold'
      inputs: 'imgMapFirst'
      timespan: 1
    - name: 'imgFoldLast'
      type: 'timeFold'
      inputs: 'imgMapLast'
      timespan: 1
    - name: 'txtUnfold'
      type: 'timeUnfold'
      inputs: 'txtSel'
      outputdEdX: false
    - name: 'txtDict'
      type: 'lut'
      inputs: 'txtUnfold'
      inputDim: 868
      outputDim: 500
      initRange: 1.0
      initSeed: 2
      learningRate: 0.0
      outputdEdX: false
    - name: 'txtFold'
      type: 'timeFold'
      inputs: 'txtDict'
      timespan: 27
      outputdEdX: false
    - name: 'concat'
      type: 'concat'
      inputs: 'imgFoldFirst, txtFold'
      axis: 1
    - name: 'concatRev'
      type: 'timeReverse'
      inputs: 'concat'
    - name: 'concatLast'
      type: 'concat'
      inputs: 'imgFoldLast, concatRev'
      axis: 1
    - name: 'concatLastRev'
      type: 'timeReverse'
      inputs: 'concatLast'
    - name: 'dropout'
      type: 'dropout'
      inputs: 'concatLastRev'
      dropoutRate: 0.2
      initSeed: 3
      outputDim: 500
    - name: 'lstm'
      type: 'lstm'
      inputs: 'dropout'
      inputDim: 500
      outputDim: 150
      timespan: 29
      initRange: 0.1
      initSeed: 4
      cutOffZeroEnd: true
      multiErr: false
      learningRate: 0.8
      learningRateAnnealConst: 0.0
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
      weightRegConst: 0.00005
      outputdEdX: true
    - name: 'softmax'
      type: 'map'
      inputs: 'lstm'
      activeFn: 'softmax'
      outputDim: 67
      initRange: 0.1
      initSeed: 7
      learningRate: 0.01
      learningRateAnnealConst: 0.0
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 15.0
      weightRegConst: 0.00005
