name: 'imgword'
costFn: 'crossEntIdx'
decisionFn: 'argmax'
stages:
    - 'imgSel'
    - 'imgFeat'
    - 'softmax'
outputs: 'softmax'
specs:
    - name: 'imgSel'
      type: 'selector'
      inputs: 'input'
      start: 0
      end: 1
      axis: 1
    - name: 'imgFeat'
      type: 'lut'
      inputs: 'imgSel'
      inputDim: 13200
      outputDim: 4096
      initWeights: '/ais/gobi3/u/mren/data/nyu-depth/hidden_oxford.h5'
      format: 'h5'
      h5key: 'hidden7'
      learningRate: 0.0
      outputdEdX: false
    - name: 'softmax'
      type: 'map'
      inputs: 'imgFeat'
      activeFn: 'softmax'
      outputDim: 67
      initRange: 0.01
      initSeed: 7
      learningRate: 0.01
      learningRateAnnealConst: 0.0
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 15.0
      weightRegConst: 0.00005