costFn: rankingLoss
decisionFn: argmax
model: all
stages:
    - name: imgUnfold
      type: timeUnfold
    - name: imgFeat
      type: lut
      inputDim: 1449
      outputDim: 4096
      initWeights: ../data/imgword/oxford-feat.npy
      learningRate: 0.0
    - name: imgMap
      type: map
      activeFn: identity
      inputDim: 4096
      outputDim: 300
      initRange: 0.1
      initSeed: 1
      learningRate: 0.8
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 50.0
    - name: imgFold
      type: timeFold
      timespan: 1
    - name: txtUnfold
      type: timeUnfold
    - name: txtDict
      type: lut
      inputDim: 871
      outputDim: 300
      initWeights: ../data/imgword/word-embed-0-q.npy
      learningRate: 0.0
    - name: txtFold
      type: timeFold
      timespan: 27
    - name: imgLine
      type: sequential
      stages:
          - imgUnfold
          - imgFeat
          - imgMap
          - imgFold
    - name: txtLine
      type: sequential
      stages:
          - txtUnfold
          - txtDict
          - txtFold
    - name: imgtxt
      type: concat
      stages:
          - imgLine
          - txtLine
      axis: 1
      splits:
          - 1
      outputdEdX: false
    - name: dropout1
      type: dropout
      dropoutRate: 0.2
      initSeed: 3
    - name: lstm1
      type: lstm
      inputDim: 300
      outputDim: 300
      timespan: 28
      initRange: 0.2
      initSeed: 4
      cutOffZeroEnd: true
      multiErr: false
      learningRate: 0.8
      learningRateAnnealConst: 0.0
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
      weightRegConst: 0.00005
      outputdEdX: true
    - name: output
      type: sequential
      stages:
          - imgtxt
          - dropout1
          - lstm1
    - name: answer
      type: constWeights
      inputDim: 300
      outputDim: 68
      #initSeed: 200
      #initRange: 0.1
      initWeights: ../data/imgword/word-embed-0-a.npy
      learningRate: 0.0
      momentum: 0.0
    - name: collector
      type: parallel
      stages:
          - answer
          - output
      axis: 0
      outputdEdX: false
    - name: cosine
      type: cosSimilarity
      bankDim: 68
    - name: all
      type: sequential
      stages:
          - collector
          - cosine
      outputdEdX: false