costFn: crossEntIdx 
decisionFn: argmax
model: all
stages:
    - name: imgUnfold
      type: timeUnfold
    - name: imgFeat
      type: lut
      inputDim: 1449
      outputDim: 4096
      initWeights: ../data/imgword/oxford-feat.npy
      learningRate: 0.0
    - name: imgMap
      type: map
      activeFn: identity
      inputDim: 4096
      outputDim: 300
      initRange: 0.1
      initSeed: 1
      learningRate: 0.8
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 50.0
    - name: imgFold
      type: timeFold
      timespan: 1
    - name: txtUnfold
      type: timeUnfold
    - name: txtDict
      type: lut
      inputDim: 871
      outputDim: 300
      initWeights: ../data/imgword/word-embed-0.npy
      learningRate: 0.0
    - name: txtFold
      type: timeFold
      timespan: 27
    - name: imgLine
      type: sequential
      stages:
          - imgUnfold
          - imgFeat
          - imgMap
          - imgFold
    - name: txtLine
      type: sequential
      stages:
          - txtUnfold
          - txtDict
          - txtFold
    - name: imgtxt
      type: parallel
      stages:
          - imgLine
          - txtLine
      axis: 1
      splits:
          - 1
      outputdEdX: false
    - name: sum
      type: timeSum
    - name: softmax
      type: map
      activeFn: softmax
      inputDim: 300
      outputDim: 68
      initRange: 0.1
      initSeed: 7
      learningRate: 0.01
      learningRateAnnealConst: 0.0
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 5.0
      weightRegConst: 0.00005
    - name: all
      type: sequential
      stages:
          - imgtxt
          - sum
          - softmax