name: 'imgword'
costFn: 'crossEntIdx'
decisionFn: 'argmax'
stages:
    - 'imgSel'
    - 'imgUnfold'
    - 'imgFeat'
    - 'imgMap'
    - 'imgFold'
    - 'txtSel'
    - 'txtUnfold'
    - 'txtDict'
    - 'txtFold'
    - 'concat'
    - 'dropout'
    - 'lstm'
    - 'softmax'
outputs: 'softmax'
specs:
    - name: 'imgSel'
      type: 'selector'
      inputs: 'input'
      start: 0
      end: 1
      axis: 1
    - name: 'txtSel'
      type: 'selector'
      inputs: 'input'
      start: 1
      end: 55
      axis: 1
    - name: 'imgUnfold'
      type: 'timeUnfold'
      inputs: 'imgSel'
      outputdEdX: false
    - name: 'imgFeat'
      type: 'lut'
      inputs: 'imgUnfold'
      inputDim: 6600
      outputDim: 4096
      initWeights: '../data/cocoqa/hidden7-toy.txt'
      format: plain
      learningRate: 0.0
      outputdEdX: false
    - name: 'imgMap'
      type: 'map'
      inputs: 'imgFeat'
      activeFn: 'identity'
      outputDim: 300
      initRange: 0.1
      initSeed: 1
      learningRate: 0.8
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 50.0
      outputdEdX: false
    - name: 'imgFold'
      type: 'timeFold'
      inputs: 'imgMap'
      timespan: 1
    - name: 'txtUnfold'
      type: 'timeUnfold'
      inputs: 'txtSel'
      outputdEdX: false
    - name: 'txtDict'
      type: 'lut'
      inputs: 'txtUnfold'
      inputDim: 4340
      outputDim: 300
      initWeights: '../data/cocoqa/word-embed-q.npy'
      learningRate: 0.0
      outputdEdX: false
    - name: 'txtFold'
      type: 'timeFold'
      inputs: 'txtDict'
      timespan: 54
      outputdEdX: false
    - name: 'concat'
      type: 'concat'
      inputs: 'imgFold, txtFold'
      axis: 1
    - name: 'dropout'
      type: 'dropout'
      inputs: 'concat'
      dropoutRate: 0.2
      initSeed: 3
      outputDim: 300
    - name: 'lstm'
      type: 'lstm'
      inputs: 'dropout'
      inputDim: 300
      outputDim: 150
      timespan: 28
      initRange: 0.2
      initSeed: 4
      cutOffZeroEnd: true
      multiErr: false
      learningRate: 0.8
      learningRateAnnealConst: 0.0
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
      weightRegConst: 0.00005
      outputdEdX: true
    - name: 'softmax'
      type: 'map'
      inputs: 'lstm'
      activeFn: 'softmax'
      outputDim: 1080
      initRange: 0.1
      initSeed: 7
      learningRate: 0.01
      learningRateAnnealConst: 0.0
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 5.0
      weightRegConst: 0.00005
