costFn: 'crossEntIdx'
decisionFn: 'argmax'
stages:
    - 'imgSel'
    - 'txtSel'
    - 'txtDict'
    - 'txtFold'
    - 'imgFeat'
    - 'imgFold'
    - 'concat'
    - 'concatRev'
    - 'concatLast'
    - 'concatLastRev'
    - 'dropoutForward'
    - 'dropoutBackward'
    - 'lstmF'
    - 'lstmB'
    - 'answer'
outputs: 'answer'
specs:
    - name: 'imgSel'
      type: 'selector'
      inputs: 'input'
      start: 0
      end: 1
      axis: 1
    - name: 'txtSel'
      type: 'selector'
      inputs: 'input'
      start: 1
      end: 40
      axis: 1
    - name: 'txtDict'
      type: 'lut'
      inputs: 'txtSel'
      inputDim: 3675
      outputDim: 500
      initRange: 1.0
      initSeed: 2
      learningRate: 0.0
      outputdEdX: false
    - name: 'txtFold'
      type: 'timeFold'
      inputs: 'txtDict'
      timespan: 39
    - name: 'imgFeat'
      type: 'lut'
      inputs: 'imgSel'
      inputDim: 13200
      outputDim: 500 
      initRange: 0.00001
      initSeed: 0
      learningRate: 0.0
      outputdEdX: false
    - name: 'imgFold'
      type: 'timeFold'
      inputs: 'imgFeat'
      timespan: 1
    - name: 'concat'
      type: 'concat'
      inputs: 'imgFold, txtFold'
      axis: 1
    - name: 'concatRev'
      type: 'timeReverse'
      inputs: 'concat'
    - name: 'concatLast'
      type: 'concat'
      inputs: 'imgFold, concatRev'
      axis: 1
    - name: 'concatLastRev'
      type: 'timeReverse'
      inputs: 'concatLast'
    - name: 'dropoutForward'
      type: 'dropout'
      inputs: 'concatLastRev'
      dropoutRate: 0.4
      initSeed: 3
      outputDim: 500
    - name: 'dropoutBackward'
      type: 'dropout'
      inputs: 'concatLast'
      dropoutRate: 0.4
      initSeed: 4
      outputDim: 500
    - name: 'lstmF'
      type: 'lstm'
      inputs: 'dropoutForward'
      inputDim: 500
      outputDim: 300
      timespan: 41
      initRange: 0.1
      initSeed: 5
      multiOutput: false
      learningRate: 0.8
      learningRateAnnealConst: 0.0
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
      weightRegConst: 0.00005
      outputdEdX: true
    - name: 'lstmB'
      type: 'lstm'
      inputs: 'dropoutBackward'
      inputDim: 500
      outputDim: 300
      timespan: 41
      initRange: 0.1
      initSeed: 6
      multiOutput: false
      learningRate: 0.8
      learningRateAnnealConst: 0.0
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
      weightRegConst: 0.00005
      outputdEdX: true
    - name: 'answer'
      type: 'map'
      inputs: 'lstmF, lstmB'
      outputDim: 239
      activeFn: 'softmax'
      initRange: 0.1
      initSeed: 6
      learningRate: 0.01
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 15.0
      weightRegConst: 0.00005
