name: 'imgword'
costFn: 'rankingLoss'
decisionFn: 'argmax'
stages:
    - 'imgSel'
    - 'imgUnfold'
    - 'imgFeat'
    - 'imgMap'
    - 'imgFold'
    - 'txtSel'
    - 'txtUnfold'
    - 'txtDict'
    - 'txtFold'
    - 'concat'
    - 'dropout'
    - 'lstm'
    - 'dropout2'
    - 'lstmOut'
    - 'answer'
    - 'collector'
    - 'cosine'
outputs: 'cosine'
specs:
    - name: 'imgSel'
      type: 'selector'
      inputs: 'input'
      start: 0
      end: 1
      axis: 1
    - name: 'txtSel'
      type: 'selector'
      inputs: 'input'
      start: 1
      end: 28
      axis: 1
    - name: 'imgUnfold'
      type: 'timeUnfold'
      inputs: 'imgSel'
      outputdEdX: false
    - name: 'imgFeat'
      type: 'lut'
      inputs: 'imgUnfold'
      inputDim: 1449
      outputDim: 4096
      initWeights: '../data/imgword/oxford-feat.npy'
      learningRate: 0.0
      outputdEdX: false
    - name: 'imgMap'
      type: 'map'
      inputs: 'imgFeat'
      activeFn: 'identity'
      outputDim: 300
      initRange: 0.1
      initSeed: 1
      learningRate: 0.2
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 50.0
      outputdEdX: false
    - name: 'imgFold'
      type: 'timeFold'
      inputs: 'imgMap'
      timespan: 1
    - name: 'txtUnfold'
      type: 'timeUnfold'
      inputs: 'txtSel'
      outputdEdX: false
    - name: 'txtDict'
      type: 'lut'
      inputs: 'txtUnfold'
      inputDim: 868
      outputDim: 300
      initWeights: '../data/imgword/word-embed-0-q.npy'
      learningRate: 0.0
      outputdEdX: false
    - name: 'txtFold'
      type: 'timeFold'
      inputs: 'txtDict'
      timespan: 27
      outputdEdX: false
    - name: 'concat'
      type: 'concat'
      inputs: 'imgFold, txtFold'
      axis: 1
    - name: 'dropout'
      type: 'dropout'
      inputs: 'concat'
      dropoutRate: 0.2
      initSeed: 3
      outputDim: 300
    - name: 'lstm'
      type: 'lstm'
      inputs: 'dropout'
      inputDim: 300
      outputDim: 300
      timespan: 28
      initRange: 0.1
      initSeed: 4
      cutOffZeroEnd: true
      multiErr: false
      learningRate: 0.2
      learningRateAnnealConst: 0.0
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
      outputdEdX: true
    - name: 'dropout2'
      type: 'dropout'
      inputs: 'lstm'
      dropoutRate: 0.5
      initSeed: 5
      outputDim: 300
    - name: 'lstmOut'
      type: 'map'
      activeFn: 'tanh'
      inputs: 'dropout2'
      outputDim: 300
      initRange: 0.1
      initSeed: 6
      learningRate: 0.1
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 10.0
      weightRegConst: 0.00005
    - name: 'answer'
      type: 'constWeights'
      inputDim: 300
      outputDim: 63
      initWeights: '../data/imgword/word-embed-0-a.npy'
      learningRate: 0.0
      momentum: 0.0
    - name: 'collector'
      type: 'concat'
      inputs: 'answer, lstmOut'
      axis: 0
    - name: 'cosine'
      type: 'cosSimilarity'
      inputs: 'collector'
      bankDim: 63
