costFn: crossEntIdx
decisionFn: argmax
model: all

stages:
    - name: 'imgSel'
      type: selectorRecurrent
      inputsStr: 'input($0)'
      start: 0
      end: 1
    - name: 'txtSel'
      type: selectorRecurrent
      inputsStr: 'input'
      start: 1
      end: 2
    - name: 'imgFeat'
      type: lutRecurrent
      inputsStr: 'imgSel($0)'
      inputDim: 1449
      outputDim: 100352
      initWeights: '../../../data/nyu-depth/hidden5_4_conv.pkl'
      sparse: true
      learningRate: 0.0
      outputdEdX: false
    - name: 'txtDict'
      type: lutRecurrent
      inputsStr: 'txtSel'
      inputDim: 871
      outputDim: 150
      initRange: 0.1
      initSeed: 3
      learningRate: 0.0
      outputdEdX: false
    - name: 'imgReshape'
      type: reshapeRecurrent
      inputsStr: 'imgFeat($0)'
      reshapeFn: '(x[0], 196, x[1]/196)'
    - name: 'attReshape'
      type: reshapeRecurrent
      inputsStr: 'attOut(-1)'
      reshapeFn: '(x[0], x[1], 1)'
    - name: 'attCtx'
      type: sumProdRecurrent
      inputsStr: 'attReshape, imgReshape($0)'
      sumAxis: 1
      outputDim: 512
    - name: 'txtAttCtx'
      type: mapRecurrent
      inputsStr: 'txtDict, attCtx'
      outputDim: 300
      activeFn: identity
      initRange: 0.1
      initSeed: 4
      learningRate: 0.1
      momentum: 0.9
      gradientClip: 0.05
      weightClip: 100
    - name: 'lstm.I'
      type: mapRecurrent
      inputsStr: 'txtAttCtx, lstm.C(-1), lstm.H(-1)'
      outputDim: 150
      activeFn: sigmoid
      initRange: 0.1
      initSeed: 6
      biasInitConst: 1.0
      learningRate: 0.1
      momentum: 0.9
      gradientClip: 0.05
      weightClip: 100
    - name: 'lstm.F'
      type: mapRecurrent
      inputsStr: 'txtAttCtx, lstm.C(-1), lstm.H(-1)'
      outputDim: 150
      activeFn: sigmoid
      initRange: 0.1
      initSeed: 6
      biasInitConst: 1.0
      learningRate: 0.1
      momentum: 0.9
      gradientClip: 0.05
      weightClip: 100
    - name: 'lstm.Z'
      type: mapRecurrent
      inputsStr: 'txtAttCtx, lstm.H(-1)'
      outputDim: 150
      activeFn: tanh
      initRange: 0.1
      initSeed: 6
      biasInitConst: 0.0
      learningRate: 0.1
      momentum: 0.9
      gradientClip: 0.05
      weightClip: 100
    - name: 'lstm.O'
      type: mapRecurrent
      inputsStr: 'txtAttCtx, lstm.C, lstm.H(-1)'
      outputDim: 150
      activeFn: sigmoid
      initRange: 0.1
      initSeed: 6
      biasInitConst: 1.0
      learningRate: 0.1
      momentum: 0.9
      gradientClip: 0.05
      weightClip: 100
    - name: 'lstm.FC'
      type: componentProdRecurrent
      inputsStr: 'lstm.F, lstm.C(-1)'
      outputDim: 150
    - name: 'lstm.IZ'
      type: componentProdRecurrent
      inputsStr: 'lstm.I, lstm.Z'
      outputDim: 150
    - name: 'lstm.C'
      type: sumRecurrent
      inputsStr: 'lstm.FC, lstm.IZ'
      numComponents: 2
      outputDim: 150
    - name: 'lstm.U'
      type: activeRecurrent
      inputsStr: 'lstm.C'
      activeFn: tanh
      outputDim: 150
    - name: 'lstm.H'
      type: componentProdRecurrent
      inputsStr: 'lstm.O, lstm.U'
      outputDim: 150
    - name: 'attHid1'
      type: mapRecurrent
      inputsStr: 'lstm.H'
      outputDim: 150
      activeFn: tanh
      initRange: 0.1
      initSeed: 6
      learningRate: 0.1
      momentum: 0.9
      gradientClip: 0.05
      weightClip: 50
    - name: 'attOut'
      type: mapRecurrent
      inputsStr: 'attHid1'
      outputDim: 196
      activeFn: softmax
      defaultValue: 0.00510204081632653
      initRange: 0.1
      initSeed: 7
      learningRate: 0.1
      momentum: 0.9
      gradientClip: 0.05
      weightClip: 50
    - name: 'attModel'
      type: recurrent
      stages:
          - 'imgSel'
          - 'txtSel'
          - 'imgFeat'
          - 'txtDict'
          - 'imgReshape'
          - 'attReshape'
          - 'attCtx'
          - 'txtAttCtx'
          - 'lstm.I'
          - 'lstm.F'
          - 'lstm.Z'
          - 'lstm.FC'
          - 'lstm.IZ'
          - 'lstm.C'
          - 'lstm.O'
          - 'lstm.U'
          - 'lstm.H'
          - 'attHid1'
          - 'attOut'
      outputStageName: 'lstm.H'
      inputDim: 2
      inputType: int
      outputDim: 150
      timespan: 27
      multiOutput: false
      outputdEdX: false
    - name: 'answer'
      type: map
      inputDim: 150
      outputDim: 63
      activeFn: softmax
      initRange: 0.1
      initSeed: 6
      learningRate: 0.01
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 10
    - name: 'all'
      type: sequential
      stages:
          - 'attModel'
          - 'answer'