costFn: 'crossEntIdx'
decisionFn: 'argmax'
stages:
    - 'imgSel1'
    - 'txtSel'
    - 'txtRev'
    - 'txtDict'
    - 'txtDictRev'
    - 'wlstm1'
    - 'wlstm1RevO'
    - 'wlstm2'
    - 'wlstm2RevO'
    - 'attModel'
    - 'answer'
outputs: 'answer'
specs:
    - name: 'imgSel1'
      type: 'selector'
      inputs: 'input'
      start: 0
      end: 1
      axis: 1
    - name: 'txtSel'
      type: 'selector'
      inputs: 'input'
      start: 1
      end: 2
      axis: 1
    - name: 'txtRev'
      type: 'timeReverse'
      inputs: 'txtSel'
      outputdEdX: false
    - name: 'txtDict'
      type: 'lut'
      inputs: 'txtSel'
      inputDim: 871
      outputDim: 300
      initWeights: '../data/imgword/word-embed-0-q.npy'
      #initRange: 0.1
      #initSeed: 3
      learningRate: 0.0
      outputdEdX: false
    - name: 'txtDictRev'
      type: 'lut'
      inputs: 'txtSelRev'
      inputDim: 871
      outputDim: 300
      initWeights: '../data/imgword/word-embed-0-q.npy'
      #initRange: 0.1
      #initSeed: 3
      learningRate: 0.0
      outputdEdX: false
    - name: 'wlstm1'
      type: 'lstm'
      inputs: 'txtDict'
      inputDim: 300
      outputDim: 150
      timespan: 27
      initRange: 0.1
      initSeed: 5
      cutOffZeroEnd: true
      multiErr: true
      learningRate: 0.8
      learningRateAnnealConst: 0.0
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
      weightRegConst: 0.00005
      outputdEdX: true
    - name: 'wlstm1RevO'
      type: 'timeReverse'
      inputs: 'wlstm1'
    - name: 'wlstm2'
      type: 'lstm'
      inputs: 'wlstm1RevO, txtDictRev'
      inputDim: 450
      outputDim: 150
      timespan: 27
      initRange: 0.1
      initSeed: 5
      cutOffZeroEnd: true
      multiErr: true
      learningRate: 0.8
      learningRateAnnealConst: 0.0
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
      weightRegConst: 0.00005
      outputdEdX: true
    - name: 'wlstm2RevO'
      type: 'timeReverse'
      inputs: 'wlstm2'
    - name: 'imgSel2'
      type: 'selector'
      inputs: 'input($0)'
      start: 0
      end: 1
    - name: 'txtSel'
      type: 'selector'
      inputs: 'input'
      start: 1
      end: 151
      recurrent: true
    - name: 'imgFeat'
      type: 'lut'
      intConversion: true
      inputs: 'imgSel2($0)'
      inputDim: 1449
      #outputDim: 1960
      outputDim: 100352
      initWeights: '../../../data/nyu-depth/hidden5_4_conv.pkl'
      #initRange: 0.1
      #initSeed: 1
      sparse: true
      learningRate: 0.0
      outputdEdX: false
      recurrent: true
    - name: 'imgReshape'
      type: 'reshape'
      inputs: 'imgFeat($0)'
      reshapeFn: '(x[0], 196, x[1]/196)'
      outputDim: 512
      recurrent: true
    - name: 'attReshape'
      type: 'reshape'
      inputs: 'attOut'
      reshapeFn: '(x[0], x[1], 1)'
      outputDim: 196
      recurrent: true
    - name: 'attCtx'
      type: 'sumProd'
      inputs: 'attReshape, imgReshape($0)'
      sumAxis: 1
      outputDim: 512
      recurrent: true
    - name: 'ctxMap'
      type: 'map'
      inputs: 'attCtx'
      outputDim: 150
      activeFn: 'tanh'
      initRange: 0.1
      initSeed: 9
      learningRate: 0.1
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 50
      recurrent: true
    - name: 'ilstm'
      type: 'lstm'
      inputs: 'ctxMap, txtSel'
      inputDim: 300
      outputDim: 150
      timespan: 27
      initRange: 0.1
      initSeed: 4
      cutOffZeroEnd: true
      multiErr: true
      learningRate: 0.8
      learningRateAnnealConst: 0.0
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 100.0
      weightRegConst: 0.00005
      outputdEdX: true
    - name: 'attHid1'
      type: 'map'
      inputs: 'txtSel, ilstm(-1)'
      outputDim: 196
      activeFn: 'tanh'
      initRange: 0.1
      initSeed: 6
      learningRate: 0.1
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 50
      recurrent: true
    - name: 'attOut'
      type: 'map'
      inputs: 'attHid1'
      outputDim: 196
      activeFn: 'softmax'
      defaultValue: 0.00510204081632653
      initRange: 0.1
      initSeed: 7
      learningRate: 0.1
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 50
      recurrent: true
    - name: 'attModel'
      type: 'recurrent'
      inputs: 'imgSel1, wlstm2RevO'
      stages:
          - 'imgSel2'
          - 'txtSel'
          - 'imgFeat'
          - 'imgReshape'
          - 'attHid1'
          - 'attOut'
          - 'attReshape'
          - 'attCtx'
          - 'attCtxMap'
          - 'ilstm'
      outputs: 'ilstm'
      inputDim: 151
      outputDim: 150
      timespan: 27
      multiOutput: false
    - name: 'answer'
      type: 'map'
      inputs: 'attModel'
      outputDim: 63
      activeFn: 'softmax'
      initRange: 0.1
      initSeed: 6
      learningRate: 0.01
      momentum: 0.9
      gradientClip: 0.1
      weightClip: 10